# 📋 BÀI TẬP 2: TRÍCH XUẤT DỮ LIỆU KHÁCH HÀNG 
**Học phần:** Phân tích kinh doanh
**Tập dữ liệu gốc:** `customer.csv` (10,108 quan sát x 16 biến)  
**Học viên:** Đỗ Văn Đạt
**Lớp:** K28.PTKDA   

---
### 🎯 Các yêu cầu thực hiện:
1. **Câu 1:** Trích xuất dữ liệu gồm các biến định tính và biến định lượng.
2. **Câu 2:** Trích xuất thông tin khách hàng đã kết hôn (`Marital_Status == 'Married'`).
3. **Câu 3:** Trích xuất thông tin khách hàng có sở hữu nhà (`House_Owner == 'yes'`).
4. **Câu 4:** Trích xuất thông tin khách hàng ở bang California (`state_cd == 'CA'`).
5. **Câu 5:** Trích xuất thông tin khách hàng trong độ tuổi từ 54 đến 64 (`Customer_Age` từ 54 - 64).

## 📦 0. Cài đặt môi trường (Nếu chưa có)
> Chạy ô code bên dưới để cài đặt `pandas`, `openpyxl` phục vụ đọc/ghi dữ liệu Excel/CSV.

In [1]:
# Tự động cài đặt thư viện vào Kernel hiện tại nếu thiếu
%pip install -q pandas openpyxl

Ghi chú: Lệnh %pip install sẽ tự động thực thi khi chạy trên Jupyter Notebook Kernel nếu thiếu thư viện.

## 🛠️ 1. Khởi tạo môi trường & Đọc dữ liệu gốc `customer.csv`

In [1]:
import pandas as pd
import numpy as np
import os

# Cấu hình hiển thị
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', lambda x: '%.4f' % x)

# Đọc dữ liệu gốc
data_path = 'customer.csv' if os.path.exists('customer.csv') else 'BA/code gửi/customer.csv'
df = pd.read_csv(data_path)

print(f"✅ Tải dữ liệu gốc thành công: {df.shape[0]:,} dòng, {df.shape[1]} cột.")
df.head()

✅ Tải dữ liệu gốc thành công: 10,108 dòng, 16 cột.

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score,Total_Trans_Ct
0,708082083,24,F,1,Uneducated,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3,42
1,708083283,62,F,0,Unknown,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2,33
2,708084558,32,F,1,Unknown,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2,20
3,708085458,38,M,2,Uneducated,Single,NY,91750,no,no,no,cellular,Blue-collar,45683,1,20
4,708086958,48,M,4,Graduate,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1,28

---
## 📌 CÂU 1: Trích xuất dữ liệu gồm các biến định tính và định lượng
> **Yêu cầu:** Phân tách và trích xuất các tập dữ liệu biến định tính (Qualitative) và biến định lượng (Quantitative), đồng thời xuất ra các file dữ liệu tương ứng.

In [2]:
# 1. Xác định danh sách các cột theo kiểu dữ liệu
quant_cols = df.select_dtypes(include=[np.number]).columns.tolist()
qual_cols = df.select_dtypes(exclude=[np.number]).columns.tolist()

print(f"• Số biến định lượng ({len(quant_cols)} biến): {quant_cols}")
print(f"• Số biến định tính ({len(qual_cols)} biến): {qual_cols}")

# 2. Trích xuất DataFrame định lượng (kèm mã khách hàng Client_Num để đối soát)
df_quantitative = df[quant_cols].copy()

# 3. Trích xuất DataFrame định tính (kèm mã khách hàng Client_Num)
df_qualitative = df[['Client_Num'] + qual_cols].copy()

# 4. Xuất file dữ liệu CSV và Excel
df_quantitative.to_csv('customer_quantitative.csv', index=False)
df_qualitative.to_csv('customer_qualitative.csv', index=False)

print("\n📁 Đã xuất 2 file thành công:")
print("  1. customer_quantitative.csv (Dữ liệu định lượng)")
print("  2. customer_qualitative.csv (Dữ liệu định tính)")

print("\n=== MẪU DỮ LIỆU ĐỊNH LƯỢNG ===")
display(df_quantitative.head())

print("\n=== MẪU DỮ LIỆU ĐỊNH TÍNH ===")
display(df_qualitative.head())

• Số biến định lượng (7 biến): ['Client_Num', 'Customer_Age', 'Dependent_Count', 'Zipcode', 'Income', 'Cust_Satisfaction_Score', 'Total_Trans_Ct']
• Số biến định tính (9 biến): ['Gender', 'Education_Level', 'Marital_Status', 'state_cd', 'Car_Owner', 'House_Owner', 'Personal_loan', 'contact', 'Customer_Job']

📁 Đã xuất 2 file thành công:
  1. customer_quantitative.csv (Dữ liệu định lượng)
  2. customer_qualitative.csv (Dữ liệu định tính)

=== MẪU DỮ LIỆU ĐỊNH LƯỢNG ===

,Client_Num,Customer_Age,Dependent_Count,Zipcode,Income,Cust_Satisfaction_Score,Total_Trans_Ct
0,708082083,24,1,91750,202326,3,42
1,708083283,62,0,91750,5225,2,33
2,708084558,32,1,91750,14235,2,20
3,708085458,38,2,91750,45683,1,20
4,708086958,48,4,91750,59279,1,28

=== MẪU DỮ LIỆU ĐỊNH TÍNH ===

,Client_Num,Gender,Education_Level,Marital_Status,state_cd,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job
0,708082083,F,Uneducated,Single,FL,no,yes,no,unknown,Businessman
1,708083283,F,Unknown,Married,NJ,no,no,no,cellular,Selfemployeed
2,708084558,F,Unknown,Married,NJ,yes,no,no,unknown,Selfemployeed
3,708085458,M,Uneducated,Single,NY,no,no,no,cellular,Blue-collar
4,708086958,M,Graduate,Single,TX,yes,yes,no,cellular,Businessman

---
## 📌 CÂU 2: Trích xuất dữ liệu khách hàng ĐÃ KẾT HÔN (`Marital_Status == 'Married'`)
> **Yêu cầu:** Lấy trích xuất dữ liệu thông tin với các khách hàng có tình trạng hôn nhân là 'Married'.

In [3]:
# Lọc khách hàng có Marital_Status là 'Married'
df_married = df[df['Marital_Status'] == 'Married'].copy()

count_married = len(df_married)
pct_married = (count_married / len(df)) * 100

print(f"💍 Số lượng khách hàng ĐÃ KẾT HÔN: {count_married:,} khách ({pct_married:.2f}% tổng số khách hàng)")

# Xuất file dữ liệu
df_married.to_csv('customer_married.csv', index=False)
print("📁 Đã lưu file: customer_married.csv")

display(df_married.head())

💍 Số lượng khách hàng ĐÃ KẾT HÔN: 5,128 khách (50.73% tổng số khách hàng)
📁 Đã lưu file: customer_married.csv

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score,Total_Trans_Ct
1,708083283,62,F,0,Unknown,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2,33
2,708084558,32,F,1,Unknown,Married,NJ,91750,yes,no,no,unknown,Selfemployeed,14235,2,20
8,708100533,48,M,2,High School,Married,NJ,91750,yes,no,no,telephone,Businessman,86668,2,24
9,708103608,53,F,1,Graduate,Married,NJ,91750,yes,yes,no,cellular,Businessman,223196,1,32
14,708117933,49,F,4,Graduate,Married,CA,91750,no,yes,no,unknown,Retirees,28122,1,29

---
## 📌 CÂU 3: Trích xuất dữ liệu khách hàng CÓ SỞ HỮU NHÀ (`House_Owner == 'yes'`)
> **Yêu cầu:** Lấy ra thông tin các khách hàng có sở hữu nhà ở.

In [4]:
# Lọc khách hàng có House_Owner là 'yes'
df_house_owner = df[df['House_Owner'].str.lower() == 'yes'].copy()

count_house = len(df_house_owner)
pct_house = (count_house / len(df)) * 100

print(f"🏠 Số lượng khách hàng SỞ HỮU NHÀ: {count_house:,} khách ({pct_house:.2f}% tổng số khách hàng)")

# Xuất file dữ liệu
df_house_owner.to_csv('customer_house_owners.csv', index=False)
print("📁 Đã lưu file: customer_house_owners.csv")

display(df_house_owner.head())

🏠 Số lượng khách hàng SỞ HỮU NHÀ: 4,718 khách (46.68% tổng số khách hàng)
📁 Đã lưu file: customer_house_owners.csv

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score,Total_Trans_Ct
0,708082083,24,F,1,Uneducated,Single,FL,91750,no,yes,no,unknown,Businessman,202326,3,42
4,708086958,48,M,4,Graduate,Single,TX,91750,yes,yes,no,cellular,Businessman,59279,1,28
5,708095133,33,F,1,High School,Single,NY,91750,no,yes,no,cellular,Selfemployeed,14254,3,24
9,708103608,53,F,1,Graduate,Married,NJ,91750,yes,yes,no,cellular,Businessman,223196,1,32
10,708104658,31,F,0,Post-Graduate,Single,CA,91750,no,yes,no,telephone,Businessman,33625,2,42

---
## 📌 CÂU 4: Trích xuất dữ liệu khách hàng ở BANG CALIFORNIA (`state_cd == 'CA'`)
> **Yêu cầu:** Lấy thông tin các khách hàng cư trú tại bang California (mã bang 'CA').

In [5]:
# Lọc khách hàng ở bang CA
df_ca = df[df['state_cd'] == 'CA'].copy()

count_ca = len(df_ca)
pct_ca = (count_ca / len(df)) * 100

print(f"🌴 Số lượng khách hàng ở BANG CALIFORNIA (CA): {count_ca:,} khách ({pct_ca:.2f}% tổng số khách hàng)")

# Xuất file dữ liệu
df_ca.to_csv('customer_california.csv', index=False)
print("📁 Đã lưu file: customer_california.csv")

display(df_ca.head())

🌴 Số lượng khách hàng ở BANG CALIFORNIA (CA): 2,468 khách (24.42% tổng số khách hàng)
📁 Đã lưu file: customer_california.csv

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score,Total_Trans_Ct
6,708098133,34,F,3,Graduate,Single,CA,91750,yes,no,no,telephone,Selfemployeed,14975,2,31
7,708099183,34,F,2,Uneducated,Single,CA,91750,no,no,no,cellular,Retirees,31982,2,36
10,708104658,31,F,0,Post-Graduate,Single,CA,91750,no,yes,no,telephone,Businessman,33625,2,42
14,708117933,49,F,4,Graduate,Married,CA,91750,no,yes,no,unknown,Retirees,28122,1,29
28,708151008,54,F,1,Uneducated,Married,CA,91750,no,yes,no,cellular,Govt,27423,2,18

---
## 📌 CÂU 5: Trích xuất dữ liệu khách hàng TRONG ĐỘ TUỔI 54 - 64
> **Yêu cầu:** Lấy thông tin các khách hàng nằm trong độ tuổi từ 54 đến 64 tuổi (`54 <= Customer_Age <= 64`).

In [6]:
# Lọc khách hàng có độ tuổi từ 54 đến 64 (inclusive)
df_age_54_64 = df[df['Customer_Age'].between(54, 64)].copy()

count_age_54_64 = len(df_age_54_64)
pct_age_54_64 = (count_age_54_64 / len(df)) * 100

print(f"🎯 Số lượng khách hàng ĐỘ TUỔI 54-64: {count_age_54_64:,} khách ({pct_age_54_64:.2f}% tổng số khách hàng)")
print(f"   • Tuổi nhỏ nhất trong tập: {df_age_54_64['Customer_Age'].min()}")
print(f"   • Tuổi lớn nhất trong tập: {df_age_54_64['Customer_Age'].max()}")

# Xuất file dữ liệu
df_age_54_64.to_csv('customer_age_54_64.csv', index=False)
print("📁 Đã lưu file: customer_age_54_64.csv")

display(df_age_54_64.head())

🎯 Số lượng khách hàng ĐỘ TUỔI 54-64: 1,804 khách (17.85% tổng số khách hàng)
   • Tuổi nhỏ nhất trong tập: 54
   • Tuổi lớn nhất trong tập: 64
📁 Đã lưu file: customer_age_54_64.csv

,Client_Num,Customer_Age,Gender,Dependent_Count,Education_Level,Marital_Status,state_cd,Zipcode,Car_Owner,House_Owner,Personal_loan,contact,Customer_Job,Income,Cust_Satisfaction_Score,Total_Trans_Ct
1,708083283,62,F,0,Unknown,Married,NJ,91750,no,no,no,cellular,Selfemployeed,5225,2,33
22,708134283,63,M,0,Graduate,Single,TX,91750,yes,yes,yes,cellular,Selfemployeed,14975,2,18
23,708136908,55,M,2,Doctorate,Married,MO,91750,yes,yes,no,cellular,Retirees,72878,2,23
26,708147108,55,F,0,Graduate,Single,NY,91750,yes,no,no,unknown,White-collar,25341,2,23
28,708151008,54,F,1,Uneducated,Married,CA,91750,no,yes,no,cellular,Govt,27423,2,18

---
## 📊 BẢNG TỔNG HỢP SO SÁNH CÁC TẬP DỮ LIỆU ĐÃ TRÍCH XUẤT
> Thống kê quy mô và đặc trưng của từng phân khúc khách hàng được trích xuất.

In [8]:
summary_extraction = pd.DataFrame({
    'Tập dữ liệu trích xuất': [
        '1. Dữ liệu gốc toàn bộ KH',
        '2. KH đã kết hôn (Married)',
        '3. KH có sở hữu nhà (House Owner)',
        '4. KH tại bang California (CA)',
        '5. KH trong độ tuổi 54 - 64'
    ],
    'Điều kiện lọc': [
        'Toàn bộ dữ liệu',
        "Marital_Status == 'Married'",
        "House_Owner == 'yes'",
        "state_cd == 'CA'",
        "54 <= Customer_Age <= 64"
    ],
    'Số lượng (khách)': [
        len(df),
        len(df_married),
        len(df_house_owner),
        len(df_ca),
        len(df_age_54_64)
    ],
    'Tỷ trọng (%)': [
        100.00,
        (len(df_married) / len(df)) * 100,
        (len(df_house_owner) / len(df)) * 100,
        (len(df_ca) / len(df)) * 100,
        (len(df_age_54_64) / len(df)) * 100
    ],
    'Tuổi TB (Mean Age)': [
        df['Customer_Age'].mean(),
        df_married['Customer_Age'].mean(),
        df_house_owner['Customer_Age'].mean(),
        df_ca['Customer_Age'].mean(),
        df_age_54_64['Customer_Age'].mean()
    ],
    'Thu nhập TB (USD)': [
        df['Income'].mean(),
        df_married['Income'].mean(),
        df_house_owner['Income'].mean(),
        df_ca['Income'].mean(),
        df_age_54_64['Income'].mean()
    ],
    'File đã xuất': [
        'customer.csv',
        'customer_married.csv',
        'customer_house_owners.csv',
        'customer_california.csv',
        'customer_age_54_64.csv'
    ]
})

display(summary_extraction)

,Tập dữ liệu trích xuất,Điều kiện lọc,Số lượng (khách),Tỷ trọng (%),Tuổi TB (Mean Age),Thu nhập TB (USD),File đã xuất
0,1. Dữ liệu gốc toàn bộ KH,Toàn bộ dữ liệu,10108,100.0000,46.2744,56976.1020,customer.csv
1,2. KH đã kết hôn (Married),Marital_Status == 'Married',5128,50.7321,46.5408,57160.4758,customer_married.csv
2,3. KH có sở hữu nhà (House Owner),House_Owner == 'yes',4718,46.6759,46.3022,55716.5170,customer_house_owners.csv
3,4. KH tại bang California (CA),state_cd == 'CA',2468,24.4163,46.2362,52377.9457,customer_california.csv
4,5. KH trong độ tuổi 54 - 64,54 <= Customer_Age <= 64,1804,17.8472,57.3570,56254.6591,customer_age_54_64.csv